name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        t: [T1037.001, T1037.002, T1037.004, T1037.005, T1053.001, T1053.002, T1053.003, T1053.004, T1053.005, T1078.001, T1078.003, T1098, T1098.004, T1133, T1136.001, T1136.002, T1137.002, T1176, T1197, T1505.001, T1505.002, T1505.003, T1543.001, T1543.002, T1543.003, T1543.004, T1546.001, T1546.003, T1546.004, T1546.005, T1546.007, T1546.008, T1546.011, T1546.012, T1546.013, T1546.014, T1547.001, T1547.004, T1547.005, T1547.006, T1547.007, T1547.009, T1547.011, T1574.001, T1574.002, T1574.006, T1574.009, T1574.011, T1574.012]
        # - T1546.002 Requires restart
        # - T1546.010 makes the following tests fail

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - run: dd if="\\.\C:" of=disk.dd bs=4096
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: disk.dd
      #     path: disk.dd
      - name: Install AtomicRedTeam
        run: |
          IEX (IWR 'https://raw.githubusercontent.com/redcanaryco/invoke-atomicredteam/master/install-atomicredteam.ps1' -UseBasicParsing)
          Install-AtomicRedTeam -getAtomics
        shell: pwsh
      - name: Get Prereqs
        run: |
          Import-Module "C:\AtomicRedTeam\invoke-atomicredteam\Invoke-AtomicRedTeam.psd1" -Force
          Invoke-AtomicTest ${{ matrix.t }} -GetPrereqs
        shell: pwsh
      - name: Run
        run: |
          Import-Module "C:\AtomicRedTeam\invoke-atomicredteam\Invoke-AtomicRedTeam.psd1" -Force
          Invoke-AtomicTest ${{ matrix.t }}
        shell: pwsh

      # Get Prereqs T1053.005-5 fails missing Word
      # Get Prereqs T1098-2 fails missing AD
      # Get Prereqs T1133-1 fails missing Chrome
      # Get Prereqs T1505.001 Missing T1505.001 yaml
      # Get Prereqs T1505.002-1 fails missing Microsoft Exchange Snap
      # Run T1053.005 yields Errors

      - name: Run autoruns
        run: |
          curl -o Autoruns.zip https://download.sysinternals.com/files/Autoruns.zip
          7z x Autoruns.zip -oAutoruns
          ./Autoruns/autorunsc64.exe -c -accepteula > autoruns.csv
        shell: bash
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.t }}-autoruns.csv
          path: autoruns.csv

      - name: Run ac
        run: |
          curl -Lo ac.zip https://github.com/forensicanalysis/artifactcollector/releases/download/v0.15.1/windows.zip
          7z x ac.zip
          ./artifactcollector.exe
          
        shell: bash
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Run discoruns
        run: |
          pip install discoruns
          discoruns --format=json forensicstore *.forensicstore > discoruns.json
        shell: bash
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.t }}-discoruns.json
          path: discoruns.json